# Generated by Django 3.2.15 on 2022-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hóspedes', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=12)),
                ('rg', models.IntegerField(verbose_name='')),
                ('nasc', models.DateField(verbose_name='')),
                ('numero_telefone', models.IntegerField(verbose_name='')),
                ('rua', models.CharField(max_length=50000)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=50000)),
                ('cidade', models.CharField(max_length=50000)),
                ('n_casa', models.IntegerField(verbose_name='')),
            ],
        ),
    ]
