# Generated by Django 3.2.15 on 2022-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomedaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='funcionários',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='')),
                ('nome', models.CharField(max_length=225)),
                ('cpf', models.CharField(max_length=12)),
                ('rg', models.IntegerField(verbose_name='')),
                ('nasc', models.DateField(verbose_name='')),
                ('numero_telefone', models.IntegerField(verbose_name='')),
                ('rua', models.CharField(max_length=225)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=225)),
                ('cidade', models.CharField(max_length=225)),
                ('n_casa', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.RenameField(
            model_name='people',
            old_name='hóspedes',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='people',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='people',
            name='n_casa',
        ),
        migrations.RemoveField(
            model_name='people',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='people',
            name='rua',
        ),
        migrations.AddField(
            model_name='estoque',
            name='codigo',
            field=models.IntegerField(verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='people',
            name='Numero_da_Casa',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='people',
            name='Observações',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='people',
            name='cidade',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='people',
            name='nasc',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='people',
            name='numero_telefone',
            field=models.IntegerField(default=''),
        ),
    ]
