# Generated by Django 3.2.15 on 2022-10-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomedaapp', '0002_auto_20221015_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
