# Generated by Django 3.2.15 on 2022-10-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomedaapp', '0003_auto_20221015_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='nasc',
        ),
        migrations.AddField(
            model_name='people',
            name='Contato_De_Emergência',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='Data_De_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='Numero_da_Casa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='numero_telefone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
