# Generated by Django 3.2.15 on 2022-10-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomedaapp', '0005_galeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
